# Generated by Django 5.1.5 on 2025-11-08 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_message_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="profiles/user-default",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
