# Generated by Django 5.1.5 on 2025-11-08 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
